version: '2'

services:
  master:
    image: chrislusf/seaweedfs # use a remote image
    container_name: seaweedfs-master
    restart: always
    ports:
      - 9333:9333
      - 19333:19333
    command: "master -ip=master"
  volume:
    image: chrislusf/seaweedfs # use a remote image
    container_name: seaweedfs-volume
    restart: always
    ports:
      - 8080:8080
      - 18080:18080
    command: 'volume -mserver="master:9333" -port=8080'
    depends_on:
      - master
  filer:
    image: chrislusf/seaweedfs # use a remote image
    container_name: seaweedfs-filer
    restart: always
    ports:
      - 8888:8888
#      - 18888:18888
    command: 'filer -master="master:9333"'
    tty: true
    stdin_open: true
    depends_on:
      - master
      - volume
