name: Test and coverage

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Go environment
        uses: actions/setup-go@v2.1.3
        with:
          # The Go version to download (if necessary) and use. Supports semver spec and ranges.
          go-version: 1.15

      - name: Run Tests
        run: go test ./... -race -coverprofile=coverage.txt -covermode=atomic

      - name: Codecov
        uses: codecov/codecov-action@v1.5.0
        with:
          # Repository upload token - get it from codecov.io. Required only for private repositories
          token: ${{ secrets.CODECOV_TOKEN }}
          # Comma-separated list of files to upload
